### ISSUE TITLE
Facebook integration

### ISSUE THREAD

**Issue by derekeder** [brentano-elementary/brentano-website#5]
Brentano has a pretty [active Facebook page](https://www.facebook.com/brentanologansquare). Let's look into pulling in their updates via the Facebook API and displaying on a news/updates page. Also would be good for the home page.

**Comment by evz** [comment]
Punting this for now until we figure out the auth stuff

**Comment by evz** [comment]
Looks like there's a way to do this with an app access token. Its a few steps but we could:

* Fetch the page feed
* Fetch the timeline album
* Make the association between photos from timeline album and posts in the feed.
* Profit?

**Comment by derekeder** [comment]
Totally integrated via dbb0e83f613328255c378a84d491c3e281199040
